import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import HeaderNavbar from '@/components/custom/HeaderNavbar'
import { LeftNavBar } from '@/components/custom/LeftNavBar'
import { ClerkProvider } from '@clerk/nextjs'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <HeaderNavbar />
          <main className='w-full h-full flex'>
            <div className='w-64'>
              <LeftNavBar />
            </div>
            <div className='flex-1'>
              {children}
            </div>
          </main>
        </body>
      </html>
    </ClerkProvider>
  )
}
